### ISSUE TITLE
Default Maven plugin : MavenMailWebCrawlerPlugin has performance issues

### ISSUE THREAD

**Issue by MadhbhavikaR** [MadhbhavikaR/WebCrawler#1]
Performance issue 10 threads with SL4J Logging
22:27:27.275 [pool-1-thread-1] DEBUG webcrawler.sdk.plugins.MavenMailWebCrawlerPlugin - [maven]took :432 seconds for :12000 files

Performance issue 10 Threads without SL4J Logging
22:53:49.969 [pool-1-thread-1] DEBUG webcrawler.sdk.plugins.MavenMailWebCrawlerPlugin - [maven]took :421 seconds for :12000 files

Too much time taken for 12000 files

**Comment by madhbhavikar** [comment]
With SL4J Logging
22:27:27.275 [pool-1-thread-1] DEBUG webcrawler.sdk.plugins.MavenMailWebCrawlerPlugin - [maven]took :432 seconds for :12000 files

**Comment by MadhbhavikaR** [comment]
Increase the number of threads in config.properties: **maven.threadPoolSize**=100 

**100 threads without SL4J Logging**
23:03:16.302 [pool-1-thread-1] DEBUG webcrawler.sdk.plugins.MavenMailWebCrawlerPlugin - [maven]took :79 seconds for :12000 files

**100 threads with SL4J Logging**
23:06:56.841 [pool-1-thread-1] DEBUG webcrawler.sdk.plugins.MavenMailWebCrawlerPlugin - [maven]took :82 seconds for :12000 files

**Comment by MadhbhavikaR** [comment]
**SL4J Logging is going to add ~11 seconds of delay on : 
Intel i5-4300U CPU @ 1.90GHz 2.49 GHz with 8GB RAM on Windows 8.1 64 bit machine**

**xxx.threadPoolSize** and **simultaneousSeeds** control the performance of the crawler
